/*
 * GeoventasAndroidAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package m664533.m88.m232.m3.controllers;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import com.fasterxml.jackson.core.type.TypeReference;
import java.util.Map;
import m664533.m88.m232.m3.ApiHelper;
import m664533.m88.m232.m3.GeoventasAndroidAPIClient;
import m664533.m88.m232.m3.exceptions.ApiException;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class AuthControllerTest extends BaseControllerTest {

    /**
     * Client instance.
     */
    private static GeoventasAndroidAPIClient client;
    
    /**
     * Controller instance (for all tests).
     */
    private static AuthController controller;

    /**
     * Setup test class.
     */
    @BeforeClass
    public static void setUpClass() {
        client = createConfiguration();
        controller = client.getAuthController();
    }

    /**
     * Tear down test class.
     */
    @AfterClass
    public static void tearDownClass() {
        controller = null;
    }

    /**
     * Testcase for testing endpoint Auth_POST.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestAuthPOST() throws Exception {
        // Parameters for the API call
        Map<String, String> body = null;

        // Set callback and perform API call
        try {
            controller.authPOST(body);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

}
