/*
 * GeoventasAndroidAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package m664533.m88.m232.m3.controllers;

import m664533.m88.m232.m3.Environment;
import m664533.m88.m232.m3.GeoventasAndroidAPIClient;
import m664533.m88.m232.m3.testing.HttpCallbackCatcher;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.rules.Timeout;

/**
 * Base class for all test cases.
 */
public class BaseControllerTest {
    /**
     * Test configuration.
     */
    public static final int REQUEST_TIMEOUT = 30;

    public static final double ASSERT_PRECISION = 0.01;
    
    /**
     * Global rules for tests.
     */
    @Rule
    public Timeout globalTimeout = Timeout.seconds(REQUEST_TIMEOUT);
    
    /**
     * Test fixtures,
     * Used to serve as HttpCallback and to capture request & response.
     */

    protected static HttpCallbackCatcher httpResponse;
    
    /**
     * Setup test.
     */
    @BeforeClass
    public static void setUp() throws Exception {
        httpResponse = new HttpCallbackCatcher(); 
    }

    /**
     * Tear down test.
     */
    @AfterClass
    public static void tearDown() throws Exception {
        httpResponse = null;
    }

    /**
     * Create test configuration from Environment variables.
     */
    protected static GeoventasAndroidAPIClient createConfigurationFromEnvironment() {
        GeoventasAndroidAPIClient.Builder builder = new GeoventasAndroidAPIClient.Builder();

        final String environment = System.getenv("GEOVENTAS_ANDROID_API_LIB_ENVIRONMENT");
        final String testServer = System.getenv("GEOVENTAS_ANDROID_API_LIB_TEST_SERVER");
        final String timeout = System.getenv("GEOVENTAS_ANDROID_API_LIB_TIMEOUT");
        final String accessToken = System.getenv("GEOVENTAS_ANDROID_API_LIB_ACCESS_TOKEN");

        if (accessToken != null) {
            builder.accessToken(accessToken);
        }
        if (environment != null) {
            builder.environment(Environment.fromString(environment));
        }
        if (testServer != null) {
            builder.testServer(testServer);
        }
        if (timeout != null) {
            builder.httpClientConfig(configBuilder -> configBuilder.timeout(
                    Long.parseLong(timeout)));
        }
        return builder.build();
    }

    
    /**
     * Create test configuration.
     */
    protected static GeoventasAndroidAPIClient createConfiguration() {
        // Set Configuration parameters for test execution
        GeoventasAndroidAPIClient config = createConfigurationFromEnvironment();
        config = config.newBuilder()
                .httpCallback(httpResponse)
                .build();
        return config;
    }
}
