/*
 * GeoventasAndroidAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package m664533.m88.m232.m3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import m664533.m88.m232.m3.internal.OptionalNullable;

/**
 * This is a model class for Credito type.
 */
public class Credito {
    private Integer id;
    private OptionalNullable<String> tipo;
    private Integer dias;
    private Double vencido;
    private Boolean bloqueoCredito;

    /**
     * Default constructor.
     */
    public Credito() {
    }

    /**
     * Initialization constructor.
     * @param  id  Integer value for id.
     * @param  tipo  String value for tipo.
     * @param  dias  Integer value for dias.
     * @param  vencido  Double value for vencido.
     * @param  bloqueoCredito  Boolean value for bloqueoCredito.
     */
    public Credito(
            Integer id,
            String tipo,
            Integer dias,
            Double vencido,
            Boolean bloqueoCredito) {
        this.id = id;
        this.tipo = OptionalNullable.of(tipo);
        this.dias = dias;
        this.vencido = vencido;
        this.bloqueoCredito = bloqueoCredito;
    }

    /**
     * Internal initialization constructor.
     */
    protected Credito(Integer id, OptionalNullable<String> tipo, Integer dias, Double vencido,
            Boolean bloqueoCredito) {
        this.id = id;
        this.tipo = tipo;
        this.dias = dias;
        this.vencido = vencido;
        this.bloqueoCredito = bloqueoCredito;
    }

    /**
     * Getter for Id.
     * @return Returns the Integer
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for Integer
     */
    @JsonSetter("id")
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Internal Getter for Tipo.
     * @return Returns the Internal String
     */
    @JsonGetter("tipo")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetTipo() {
        return this.tipo;
    }

    /**
     * Getter for Tipo.
     * @return Returns the String
     */
    public String getTipo() {
        return OptionalNullable.getFrom(tipo);
    }

    /**
     * Setter for Tipo.
     * @param tipo Value for String
     */
    @JsonSetter("tipo")
    public void setTipo(String tipo) {
        this.tipo = OptionalNullable.of(tipo);
    }

    /**
     * UnSetter for Tipo.
     */
    public void unsetTipo() {
        tipo = null;
    }

    /**
     * Getter for Dias.
     * @return Returns the Integer
     */
    @JsonGetter("dias")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getDias() {
        return dias;
    }

    /**
     * Setter for Dias.
     * @param dias Value for Integer
     */
    @JsonSetter("dias")
    public void setDias(Integer dias) {
        this.dias = dias;
    }

    /**
     * Getter for Vencido.
     * @return Returns the Double
     */
    @JsonGetter("vencido")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getVencido() {
        return vencido;
    }

    /**
     * Setter for Vencido.
     * @param vencido Value for Double
     */
    @JsonSetter("vencido")
    public void setVencido(Double vencido) {
        this.vencido = vencido;
    }

    /**
     * Getter for BloqueoCredito.
     * @return Returns the Boolean
     */
    @JsonGetter("bloqueoCredito")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getBloqueoCredito() {
        return bloqueoCredito;
    }

    /**
     * Setter for BloqueoCredito.
     * @param bloqueoCredito Value for Boolean
     */
    @JsonSetter("bloqueoCredito")
    public void setBloqueoCredito(Boolean bloqueoCredito) {
        this.bloqueoCredito = bloqueoCredito;
    }

    /**
     * Converts this Credito into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Credito [" + "id=" + id + ", tipo=" + tipo + ", dias=" + dias + ", vencido="
                + vencido + ", bloqueoCredito=" + bloqueoCredito + "]";
    }

    /**
     * Builds a new {@link Credito.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Credito.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .dias(getDias())
                .vencido(getVencido())
                .bloqueoCredito(getBloqueoCredito());
        builder.tipo = internalGetTipo();
        return builder;
    }

    /**
     * Class to build instances of {@link Credito}.
     */
    public static class Builder {
        private Integer id;
        private OptionalNullable<String> tipo;
        private Integer dias;
        private Double vencido;
        private Boolean bloqueoCredito;



        /**
         * Setter for id.
         * @param  id  Integer value for id.
         * @return Builder
         */
        public Builder id(Integer id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for tipo.
         * @param  tipo  String value for tipo.
         * @return Builder
         */
        public Builder tipo(String tipo) {
            this.tipo = OptionalNullable.of(tipo);
            return this;
        }

        /**
         * UnSetter for tipo.
         * @return Builder
         */
        public Builder unsetTipo() {
            tipo = null;
            return this;
        }

        /**
         * Setter for dias.
         * @param  dias  Integer value for dias.
         * @return Builder
         */
        public Builder dias(Integer dias) {
            this.dias = dias;
            return this;
        }

        /**
         * Setter for vencido.
         * @param  vencido  Double value for vencido.
         * @return Builder
         */
        public Builder vencido(Double vencido) {
            this.vencido = vencido;
            return this;
        }

        /**
         * Setter for bloqueoCredito.
         * @param  bloqueoCredito  Boolean value for bloqueoCredito.
         * @return Builder
         */
        public Builder bloqueoCredito(Boolean bloqueoCredito) {
            this.bloqueoCredito = bloqueoCredito;
            return this;
        }

        /**
         * Builds a new {@link Credito} object using the set fields.
         * @return {@link Credito}
         */
        public Credito build() {
            return new Credito(id, tipo, dias, vencido, bloqueoCredito);
        }
    }
}
