/*
 * GeoventasAndroidAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package m664533.m88.m232.m3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;
import m664533.m88.m232.m3.internal.OptionalNullable;

/**
 * This is a model class for JerarquiaPrincipal type.
 */
public class JerarquiaPrincipal {
    private Integer id;
    private OptionalNullable<String> nombre;
    private OptionalNullable<List<JerarquiaSecundaria>> jerarquiasSecundarias;

    /**
     * Default constructor.
     */
    public JerarquiaPrincipal() {
    }

    /**
     * Initialization constructor.
     * @param  id  Integer value for id.
     * @param  nombre  String value for nombre.
     * @param  jerarquiasSecundarias  List of JerarquiaSecundaria value for jerarquiasSecundarias.
     */
    public JerarquiaPrincipal(
            Integer id,
            String nombre,
            List<JerarquiaSecundaria> jerarquiasSecundarias) {
        this.id = id;
        this.nombre = OptionalNullable.of(nombre);
        this.jerarquiasSecundarias = OptionalNullable.of(jerarquiasSecundarias);
    }

    /**
     * Internal initialization constructor.
     */
    protected JerarquiaPrincipal(Integer id, OptionalNullable<String> nombre,
            OptionalNullable<List<JerarquiaSecundaria>> jerarquiasSecundarias) {
        this.id = id;
        this.nombre = nombre;
        this.jerarquiasSecundarias = jerarquiasSecundarias;
    }

    /**
     * Getter for Id.
     * @return Returns the Integer
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for Integer
     */
    @JsonSetter("id")
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Internal Getter for Nombre.
     * @return Returns the Internal String
     */
    @JsonGetter("nombre")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetNombre() {
        return this.nombre;
    }

    /**
     * Getter for Nombre.
     * @return Returns the String
     */
    public String getNombre() {
        return OptionalNullable.getFrom(nombre);
    }

    /**
     * Setter for Nombre.
     * @param nombre Value for String
     */
    @JsonSetter("nombre")
    public void setNombre(String nombre) {
        this.nombre = OptionalNullable.of(nombre);
    }

    /**
     * UnSetter for Nombre.
     */
    public void unsetNombre() {
        nombre = null;
    }

    /**
     * Internal Getter for JerarquiasSecundarias.
     * @return Returns the Internal List of JerarquiaSecundaria
     */
    @JsonGetter("jerarquiasSecundarias")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<List<JerarquiaSecundaria>> internalGetJerarquiasSecundarias() {
        return this.jerarquiasSecundarias;
    }

    /**
     * Getter for JerarquiasSecundarias.
     * @return Returns the List of JerarquiaSecundaria
     */
    public List<JerarquiaSecundaria> getJerarquiasSecundarias() {
        return OptionalNullable.getFrom(jerarquiasSecundarias);
    }

    /**
     * Setter for JerarquiasSecundarias.
     * @param jerarquiasSecundarias Value for List of JerarquiaSecundaria
     */
    @JsonSetter("jerarquiasSecundarias")
    public void setJerarquiasSecundarias(List<JerarquiaSecundaria> jerarquiasSecundarias) {
        this.jerarquiasSecundarias = OptionalNullable.of(jerarquiasSecundarias);
    }

    /**
     * UnSetter for JerarquiasSecundarias.
     */
    public void unsetJerarquiasSecundarias() {
        jerarquiasSecundarias = null;
    }

    /**
     * Converts this JerarquiaPrincipal into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "JerarquiaPrincipal [" + "id=" + id + ", nombre=" + nombre
                + ", jerarquiasSecundarias=" + jerarquiasSecundarias + "]";
    }

    /**
     * Builds a new {@link JerarquiaPrincipal.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link JerarquiaPrincipal.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId());
        builder.nombre = internalGetNombre();
        builder.jerarquiasSecundarias = internalGetJerarquiasSecundarias();
        return builder;
    }

    /**
     * Class to build instances of {@link JerarquiaPrincipal}.
     */
    public static class Builder {
        private Integer id;
        private OptionalNullable<String> nombre;
        private OptionalNullable<List<JerarquiaSecundaria>> jerarquiasSecundarias;



        /**
         * Setter for id.
         * @param  id  Integer value for id.
         * @return Builder
         */
        public Builder id(Integer id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for nombre.
         * @param  nombre  String value for nombre.
         * @return Builder
         */
        public Builder nombre(String nombre) {
            this.nombre = OptionalNullable.of(nombre);
            return this;
        }

        /**
         * UnSetter for nombre.
         * @return Builder
         */
        public Builder unsetNombre() {
            nombre = null;
            return this;
        }

        /**
         * Setter for jerarquiasSecundarias.
         * @param  jerarquiasSecundarias  List of JerarquiaSecundaria value for
         *         jerarquiasSecundarias.
         * @return Builder
         */
        public Builder jerarquiasSecundarias(List<JerarquiaSecundaria> jerarquiasSecundarias) {
            this.jerarquiasSecundarias = OptionalNullable.of(jerarquiasSecundarias);
            return this;
        }

        /**
         * UnSetter for jerarquiasSecundarias.
         * @return Builder
         */
        public Builder unsetJerarquiasSecundarias() {
            jerarquiasSecundarias = null;
            return this;
        }

        /**
         * Builds a new {@link JerarquiaPrincipal} object using the set fields.
         * @return {@link JerarquiaPrincipal}
         */
        public JerarquiaPrincipal build() {
            return new JerarquiaPrincipal(id, nombre, jerarquiasSecundarias);
        }
    }
}
